/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'rate' : IDL.Nat,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CartItem = IDL.Record({
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const Time = IDL.Int;
export const Order = IDL.Record({
  'id' : IDL.Text,
  'total' : IDL.Nat,
  'timestamp' : Time,
  'items' : IDL.Vec(CartItem),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'addToCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([], [], []),
  'removeFromCart' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'rate' : IDL.Nat,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CartItem = IDL.Record({ 'productId' : IDL.Text, 'quantity' : IDL.Nat });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'id' : IDL.Text,
    'total' : IDL.Nat,
    'timestamp' : Time,
    'items' : IDL.Vec(CartItem),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'addToCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([], [], []),
    'removeFromCart' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };